#!/bin/bash
for f in *.[Fh]90
do
echo $f >> newsubmod.list
grep -e'^ *SUBROUTINE' -e'FUNCTION' -e'^ *MODULE' -e'CONTAINS' -e'^ *INTERFACE' -e'^ *RECURSIVE SUB' $f \
        | grep -v 'END FUNCT' | grep -v '^#' | grep -v 'PROCEDURE' \
        | sed -e 's/(.*) FUN/ FUN/1' | sed -e 's/(.*)//' | sed -e 's/(.*$//' | grep -v '^ *!' >> newsubmod.list
echo " "  >> newsubmod.list
done
